import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['500', '600', '700', '800', '900']
})

export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} font-bold antialiased`}>
        {children}
      </body>
    </html >
  );
}
